#! /bin/sh

sxhkd &
wmname LG3D &
feh --bg-fill ~/Pictures/wallpaper.png &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


~/.config/polybar/launch.sh &